config/routes.rb
Rails.application.routes.draw do

  resources :people do
    get 'enable'
  end

  devise_for :users
  get 'welcome/index'
  resources :groups do
    get 'new_project'
    get 'projects'
    get 'people'
    get 'enable'
  end
  resources :projects do
    get 'enable'
  end
  resources :assignments

  root 'groups#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  acts_as_xlsx
  belongs_to :group
  belongs_to :project
  belongs_to :person


  validates :group_id, :project_id, :person_id, :startdate, :enddate, :active, :presence => true
  validates :allocation, :presence => true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  def deactive
    person = Person.find(self.person_id)
    newAllocation = person.allocation
    newAllocation -= self.allocation
    person.update_column :allocation, newAllocation
    self.update_column :enddate, Time.now
    self.update_column :active, false
  end
  
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
    @people = Person.where(:active => true)
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  def create
    @assignment = Assignment.new(assignment_params)
    @person = Person.find(params[:assignment][:person_id])
    @person.allocation += params[:assignment][:allocation].to_i
    if @assignment.save
      @person.save
      redirect_to person_path(@person), :notice => "created"
    else
      redirect_to person_path(@person), :notice => 'Not created'
    end
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
    @persons = Person.all
    @projects = Project.all
  end

  # GET /assignments/1/edit
  def edit
    @persons = Person.all
    @projects = Project.all
  end

  # POST /assignments
  # POST /assignments.json
  

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
      @previousAllocation = @assignment.allocation
      @person = Person.find(@assignment.person_id)
      if @assignment.update(assignment_params)
        @person.allocation -= @previousAllocation
        @person.allocation += @assignment.allocation
        @person.save
        redirect_to person_path(@person)
      else
        redirect_to person_path(@person)
      end
   
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    #Rails.logger.info "---------------------------------"
    #@assignment.active = false
    # @assignment.update_column :active, false
    @person = Person.find(@assignment.person_id)
    # @person.allocation -= @assignment.allocation
    # if @person.save
    #   if @assignment.save 
    #     redirect_to person_path(@person)
    #   else
    #     redirect_to person_path(@person)
    #   end
    # else
    #   redirect_to person_path(@person)
    # end
    if @assignment.deactive
      redirect_to person_path(@person)
    else
      redirect_to person_path(@person)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:person_id, :project_id, :billable, :group_id,:allocation,:startdate, :enddate)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
	def getProjectStatus(person_id)
		@assignments = Assignment.where(:person_id => person_id,:active => true)
		@status = false
		@t = @assignments.order(:enddate).first
		Rails.logger.info "-------------------------------#{@t}"
		#@assignments.each do |assignment|
			#@status = @status || Project.find(assignment.project_id).active
		#end
		#if @status
		#@firstAssignment.id
		if (@t.class == Assignment ) && ((@t.enddate - Time.now) < 7.days)
			"Success"
		else
			"Active"		
		end
	end
end

app/views/assignments/_index.html.erb
<div class="container mainContent">
  <div>
    <h3>Allocation Index</h3>
    <%#= link_to "Excel", controller: "groups", action: "show", id: @group, format: "xls" %>
    <%= link_to controller: "groups", action: "show", id: @group, format: "xlsx" do  %>
      <i class="glyphicon glyphicon-download-alt"></i>Download as Excel
    <% end %>
    <%#= link_to "Download as Excel", controller: "groups", action: "show", id: @group, format: "xlsx" %>
  </div>
  <ul class="nav nav-tabs" id="peopleTab">
    <li class="active"><a href="#unallocatedPersons" title="Unallocated People">Unallocated People</a></li>
    <li><a href="#allocatedPersons" title="Allocated People">Allocated People</a></li>
  </ul>

  <div id='content' class="tab-content">
    <div class="tab-pane active" id="unallocatedPersons">
      <table class="data table table-hover">
        <thead>
            <th>Assignment ID/s</th>
            <th>Name</th>
            <th>Project</th>
            <th>Billable</th>
            <th>Allocation</th>
        </thead>
       
        <% @people.each do |person| %>
            <% if (person.allocation != 100) && (person.allocation != 0) && (person.active?) %>
              <% @assignments = Assignment.where(person_id: person.id) %>

                <tr class="<%= getProjectStatus(person.id) %>"><td>
                <% @assignments.each do |assignment| %>
                  <%= assignment.id %><br>
                <% end %></td>
                  <td><a href="<%= person_path(person) %>" title="<%= person.name %>"><%= person.name %></a></td>
                <td><% @assignments.each do |assignment| %>  
                  
                  <a href="<%= project_path(Project.find(assignment.project_id)) %>"><%= Project.find(assignment.project_id).name %></a><br>
                  
                  
                <% end %></td><td>
                <% @finalBillable = false %>
                <% @assignments.each do |assignment| %>
                  <% @finalBillable = @finalBillable || assignment.billable %>
                <% end %>
                <%= @finalBillable ? 'Yes' : 'No' %><br>
                </td>
                <td><% @assignments.each do |assignment| %>
                  <%= assignment.allocation %><br>
                <% end %></td>
                </tr> 
               


            <% end %>
          <% end %>
          <% @people.each do |person| %>
            <% if (person.allocation == 0) %>
              <tr class="<%= getProjectStatus(person.id) %>">
                <td><%= "NA" %></td>
                <td><a href="<%= person_path(person) %>" title="<%= person.name %>"><%= person.name %></a></td>
                <td>
                <%= "Not Assigned" %>                 
                </td>
                <td><%= "NA" %></td>
                <td><%= 0 %></td>
              </tr> 
            <% end %>
          <% end %>
        </table>
    </div>
    <div class="tab-pane" id="allocatedPersons">
      <table class="data table table-striped">
        <thead>
            <th>Assignment ID/s</th>
            <th>Name</th>
            <th>Project</th>
            <th>Billable</th>
            <th>Allocation</th>
        </thead>
       
        <% @people.each do |person| %>
            <% if (person.allocation == 100) %>
              <% @assignments = Assignment.where(person_id: person.id) %>

              
                <tr><td>
                <% @assignments.each do |assignment| %>
                  <%= assignment.id %><br>
                <% end %></td>
                  <td><a href="<%= person_path(person) %>" title="<%= person.name %>"><%= person.name %></a></td>
                <td><% @assignments.each do |assignment| %>  
                  
                  <a href="<%= project_path(Project.find(assignment.project_id)) %>"><%= Project.find(assignment.project_id).name %></a><br>
                  
                  
                <% end %></td><td>
                  <% @finalBillable = false %>
                  <% @assignments.each do |assignment| %>
                    <% @finalBillable = @finalBillable || assignment.billable %>
                  <% end %>
                  <%= @finalBillable ? 'Yes' : 'No' %><br>
                </td>
                <td><% @assignments.each do |assignment| %>
                  <%= assignment.allocation %><br>
                <% end %></td>
                </tr> 
               


            <% end %>
          <% end %>
        </table> 
    </div>
  </div>
</div>

app/views/assignments/edit.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
  <strong>ID:</strong>
  <%= @assignment.id %>
  </p>
  <div class="field">
    <%= f.label :billable %><br>
    <%= f.check_box :billable %>
  </div>
  <p>
  <strong>Group ID:</strong>
  <%= @assignment.group_id %>
</p>

<p>
  <strong>Project ID:</strong>
  <%= @assignment.project_id %>
</p>

<p>
  <strong>Person ID:</strong>
  <%= @assignment.person_id %>
</p>
  <div class="field">
    <%= f.label :allocation %><br>
    <%= f.text_field :allocation %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.text_field :startdate  , :class => 'datepicker' %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br>
    <%= f.text_field :enddate  , :class => 'datepicker' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/index.html.erb
<table class="data table table-striped">
          <thead>
              <th>Assignment ID/s</th>
              <th>Show</th>
              <th>Edit</th>
              <th>Delete</th>
          </thead>
<% @assignments.each do |assignment| %>
<tr>
<td><%= assignment.id %></td>
<td><%= link_to 'show',assignment_path(assignment) %></td>>
<td><%= link_to 'edit',edit_assignment_path(assignment) %></td>
<td><%= link_to 'delete',assignment_path(assignment),method: :delete ,data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>

<script type="text/javascript">
$('.data').dataTable();
</script>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>ID:</strong>
  <%= @assignment.id %>
</p>

<p>
  <strong>Billable:</strong>
  <%= @assignment.billable %>
</p>

<p>
  <strong>Group ID:</strong>
  <%= @assignment.group_id %>
</p>

<p>
  <strong>Project ID:</strong>
  <%= @assignment.project_id %>
</p>

<p>
  <strong>Person ID:</strong>
  <%= @assignment.person_id %>
</p>

<p>
  <strong>Allocation:</strong>
  <%= @assignment.allocation %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @assignment.startdate %>
</p>
<p>
  <strong>End Date :</strong>
  <%= @assignment.enddate %>
</p>