config/routes.rb
Rails.application.routes.draw do

  resources :people do
    get 'enable'
  end

  devise_for :users
  get 'welcome/index'
  resources :groups do
    get 'new_project'
    get 'projects'
    get 'people'
    get 'enable'
  end
  resources :projects do
    get 'enable'
  end
  resources :assignments

  root 'groups#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
	acts_as_xlsx
  	belongs_to :group
  	
  	validates :name, :presence => true, :length => { :minimum => 2 }
	validates :skills, :presence => true, :length => { :minimum => 8 }
	validates :totalExp, :tcsExp, :relExp, :presence => true, :numericality => { :greater_than_or_equal_to => 0 }
	validates :mobilenumber, :presence => true
	validates_format_of :mobilenumber, :with => /\A\d{10}\Z/
	validates :allocation, :active, :group_id, :location, :emailid, :presence => true
	validates_format_of :emailid, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates :interestAreas, :presence => true, :length => { :minimum => 8 }

	def deactive
	  self.update_column :active, false
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	before_action :authenticate_user!
	before_action :set_person, only: [:show, :edit, :update, :destroy]

	def index
		@people = Person.all
	end

	def new
		#@person = Person.new
		#@groups = Group.all 
	end

	def checkMailID
		emailExist = Person.find_by_email(params[:checkmail]).present?
	end

	def create
		@group = Group.find(params[:person][:group_id])
		@person = Person.new(person_params)
		@deviseUser = User.create_new_user(params[:person][:emailid])
		#UserMailer.welcome_email(@personnew).deliver
		if @person.save
			redirect_to group_people_path(@group)
		else
			redirect_to group_people_path(@group)
		end
	end

	def edit
		#@groups = Group.all
	end

	def update
		#@group = Group.find(params[:person][:group_id])
		if @person.update(person_params)
			redirect_to person_path(@person)
		else
			redirect_to person_path(@person)
		end
	end

	def show
		#@assignment = Assignment.new
		#@people = Person.all
		@projects = Project.where(:group_id => @person.group_id) 
		@assignments = Assignment.where(:person_id => @person.id)
		@group = Group.find(@person.group_id)
		#@project = Project.new
	end

	def destroy
		@openAssignments = Assignment.where(:person_id => @person.id, :active => true)
		#@openAssignments = openAssignments.where("enddate > ?", Time.now)
   		if (!@openAssignments.empty?)
   			@openAssignments.each do |openAssignment|
   				openAssignment.deactive
   			end
   		end

		if @person.deactive
			redirect_to person_path(@person)
		else
			redirect_to person_path(@person)
		end
	end

	def enable
		@person = Person.find(params[:person_id])
		@person.update_column :active, true
		#@person.active = true
		if @person.save 
			redirect_to person_path(@person)
		else
			redirect_to person_path(@person)
		end
	end

	private
		def set_person
			@person = Person.find(params[:id])
		end

		def person_params
      		params.require(:person).permit(:name, :skills, :totalExp, :tcsExp, :relExp, :mobilenumber,  :emailid,  :allocation, :interestAreas, :group_id, :active,:location,:PersonalLearnings)
    	end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_index.html.erb
<div class="col-md-12">
  <div class="table-responsive">
    <table class="data table table-striped">
        <thead>
            <th>Name</th>
            <th>Skill</th>
            <th>Relevent Exp.</th>
            <th>Allocation</th>
            <th>Active</th>
            <th>Location</th>
            <% if current_user.admin %>
            <th>Disable</th>
            <% end %>
        </thead>
        <% @people.each do |person| %>
          <%# if person.active? %>
          <% if @group.id == person.group_id %>
            <tr>
              <td><a href="<%= person_path(person) %>"><%= person.name %></a></td>
              <td><%= person.skills %></td>
              <td><%= person.relExp %></td>
              <td><%= person.allocation %></td>
              <td><%= person.active ? "Yes" : "No" %></td>
              <td><%= person.location %></td>

              <% if current_user.admin %>
              <% if person.active? %>
              <td><%= link_to person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" do  %>
                <i class="glyphicon glyphicon-ban-circle"></i>
                <% end %>
              </td>
              <% else %>
              <td><%= link_to person_enable_path(person), data: { confirm: 'Are you sure?' } , class: "btn btn-default" do  %>
                <i class="glyphicon glyphicon-ok-circle"></i>
                <% end %>
              </td>
              <% end %>
              <% end %>
            </tr>
          <% end %>    
          <% end %> 
        </table>
        </div>

  </div>
</div>

app/views/people/_new.html.erb
<%= form_for(@person) do |f| %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_area :skills %>
  </div>
  <div class="field">
    <%= f.label :location %><br> 
    <select id="person_location" name="person[location]">
      <option value="Mumbai">Mumbai</option>
      <option value="Banglore">Banglore</option>
      <option value="Gurgaon">Gurgaon</option>
      <option value="Kolkata">Kolkata</option>
      <option value="NYC">NYC</option>
    </select>
  </div>
  <div class="field">
    <%= f.label :totalExp %><br>
    <%= f.text_field :totalExp %>
  </div>
  <div class="field">
    <%= f.label :tcsExp %><br>
    <%= f.text_field :tcsExp %>
  </div>
  <div class="field">
    <%= f.label :relExp %><br>
    <%= f.text_field :relExp %>
  </div>
  <input type="hidden" name="person[allocation]" value="<%= 0 %>">
  <div class="field">
    <%= f.label :mobilenumber %><br>
    <%= f.number_field :mobilenumber %>
  </div>
  <div class="field">
    <%= f.label :emailid %><br>
    <%= f.text_field :emailid %>
  </div>
  <div class="field">
    <%= f.label :interestAreas %><br>
    <%= f.text_area :interestAreas %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <input type="hidden" name="person[group_id]" value="<%= @group.id %>">
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_area :skills %>
  </div>
  <div class="field">
    <%= f.label :Location %><br>
    <select id="person_location" name="person[location]">
      <option value="Mumbai" <%= "selected" if @person.location == "Mumbai" %> >Mumbai</option>
      <option value="Banglore" <%= "selected" if @person.location == "Banglore" %> >Banglore</option>
      <option value="Gurgaon" <%= "selected" if @person.location == "Gurgaon" %> >Gurgaon</option>
      <option value="Kolkata" <%= "selected" if @person.location == "Kolkata" %> >Kolkata</option>
      <option value="NYC" <%= "selected" if @person.location == "NYC" %> >NYC</option>
    </select>
  </div>
  <div class="field">
    <%= f.label :totalExp %><br>
    <%= f.text_field :totalExp %>
  </div>
  <div class="field">
    <%= f.label :tcsExp %><br>
    <%= f.text_field :tcsExp %>
  </div>
  <div class="field">
    <%= f.label :releventExp %><br>
    <%= f.text_field :relExp %>
  </div>
  <div class="field">
    <%= f.label :allocation %><br>
    <%= f.number_field :allocation ,:disabled=>true %>
  </div>
  <div class="field">
    <%= f.label :mobilenumber %><br>
    <%= f.number_field :mobilenumber %>
  </div>
  <div class="field">
    <%= f.label :emailid %><br>
    <%= f.text_field :emailid %>
  </div>
  <div class="field">
    <%= f.label :interestAreas %><br>
    <%= f.text_area :interestAreas %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.label Group.find(@person.group_id).name %>
    <input type="hidden" name="person[group_id]" value="<%= @person.group_id %>">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/index.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <div class="table-responsive">
    <table class="data table table-striped">
        <thead>
            <th>Name</th>
            <th>Skills</th>
            <th>Totalexp</th>
            <th>Tcsexp</th>
            <th>Releventexp</th>
            <th>Allocation</th>
            <th>Active</th>
            <th>Location</th>
            <th>Group</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
       
        <% @people.each do |person| %>
          <%# if person.active? %>
            <tr>
              <td><a href="<%= person_path(person) %>"><%= person.name %></a></td>
              <td><%= person.skills %></td>
              <td><%= person.totalExp %></td>
              <td><%= person.tcsExp %></td>
              <td><%= person.relExp %></td>
              <td><%= person.allocation %></td>
              <td><%= person.active %></td>
              <td><%= person.location %></td>
              <td><%= Group.find(person.group_id).name %></td>
              <td><%= link_to 'Show', person %></td>
              <td><%= link_to 'Edit', edit_person_path(person) %></td>
              <% if person.active? %>
              <td><%= link_to 'Disable', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% else %>
              <td><%= link_to 'Enable', person_enable_path(person), data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
          <%# end %>    
          <% end %> 
        </table>
        </div>
  </div>
</div>

app/views/people/new.html.erb
<%= form_for(@person) do |f| %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_area :skills %>
  </div>
  <div class="field">
    <%= f.label :location %><br>

    <select id="person_location" name="person[location]">
      <option value="Mumbai">Mumbai</option>
      <option value="Banglore">Banglore</option>
      <option value="Gurgaon">Gurgaon</option>
      <option value="Kolkata">Kolkata</option>
      <option value="NYC">NYC</option>
    </select>
  </div>
  <div class="field">
    <%= f.label :totalExp %><br>
    <%= f.text_field :totalExp %>
  </div>
  <div class="field">
    <%= f.label :tcsExp %><br>
    <%= f.text_field :tcsExp %>
  </div>
  <div class="field">
    <%= f.label :relExp %><br>
    <%= f.text_field :relExp %>
  </div>
  <div class="field">
    <%= f.label :allocation %><br>
    <%= f.number_field :allocation %>
  </div>
  <div class="field">
    <%= f.label :mobilenumber %><br>
    <%= f.number_field :mobilenumber %>
  </div>
  <div class="field">
    <%= f.label :emailid %><br>
    <%= f.text_field :emailid %>
  </div>
  <div class="field">
    <%= f.label :interestAreas %><br>
    <%= f.text_area :interestAreas %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%#= f.text_field :group_id %>
    <select id="person_group_id" name="person[group_id]">
      <% @groups.each do |group| %>
        <option value="<%= group.id %>">
          <%= group.name %>
        </option>
      <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/show.html.erb
<div class="col-md-2">
  <%= render 'groups/sidebar' %>
</div>

<div class="col-md-4">
  <table class="table table-striped">
    <tr>
      <td><strong>Name:</strong></td>
      <td><%= @person.name %></td>
    </tr>

    <tr>
      <td><strong>Skills:</strong></td>
      <td><%= @person.skills %></td>
    </tr>

    <tr>
      <td><strong>Totalexp:</strong></td>
      <td><%= @person.totalExp %></td>
    </tr>

    <tr>
      <td><strong>Tcsexp:</strong></td>
      <td><%= @person.tcsExp %></td>
    </tr>

    <tr>
      <td><strong>Releventexp:</strong></td>
      <td><%= @person.relExp %></td>
    </tr>

    <tr>
      <td><strong>Allocation:</strong></td>
      <td><%= @person.allocation %></td>
    </tr>

    <tr>
      <td><strong>Location:</strong></td>
      <td><%= @person.location %></td>
    </tr>

    <tr>
      <td><strong>Mobile Number :</strong></td>
      <td><%= @person.mobilenumber %></td>
    </tr>

    <tr>
      <td><strong>Email ID:</strong></td>
      <td><%= @person.emailid %></td>
    </tr>

    <tr>
      <td><strong>Interestareas:</strong></td>
      <td><%= @person.interestAreas %></td>
    </tr>

    <tr>
      <td><strong>Active:</strong></td>
      <td><%= @person.active == true ? "Yes" : "No" %></td>
    </tr>

    <tr>
      <td><strong>Group:</strong></td>
      <td><%= Group.find(@person.group_id).name %></td>
    </tr>

    <tr>
      <td><strong>Personal Learnings :</strong></td>
      <td><%= @person.PersonalLearnings %></td>
    </tr>
  </table>
  <hr>
          
  <% if current_user.admin %>
    <% if @person.allocation < 100 && @person.active? %>
      <a href="#" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#newAssignmentModal">Assign a Project</a>
    <% end %>    
    <% if @person.active? %>
      <%= link_to "Disable", @person ,  :class=> "btn btn-sm btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
    <% else %>
      <%= link_to 'Enable',person_enable_path(@person), :class=> "btn btn-sm btn-primary", data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>
  
  <% if (current_user.email == @person.emailid) ||  current_user.admin %> 
      <a href="#" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#editPersonModal">Edit Details</a>
  <% end %>


  <div class="modal" id="newAssignmentModal" tabindex="-1" role="dialog" aria-labelledby="newAssignmentModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
          <h4 class="modal-title" id="myModalLabel">New Assignment</h4>
        </div>
        <div class="modal-body">
          <%= form_for(Assignment.new) do |f| %>
            <div class="field">
              <%= f.label :person_id %> : 
              <input type="hidden" name="assignment[person_id]" value="<%= @person.id %>">
              <%= f.label @person.name %><br>
            </div>
            <input type="hidden" name="assignment[group_id]" value="<%= @person.group_id %>">
            <div class="field">
              <%= f.label :project_id %><br>
              <%= f.select :project_id, options_from_collection_for_select(getGroupProjects(@person.group_id), "id", "name"),{},{:class => 'input-xlarge'} %>
            </div>
            <div class="field">
              <%= f.label :billable %><br>
              <%= f.check_box :billable %>
            </div>           
            <div class="field">
              <%= f.label :startdate %><br>
              <%= f.text_field :startdate, :class => 'input-xlarge datepicker',:readonly => 'true' %>
            </div>
            <div class="field">
              <%= f.label :enddate %><br>
              <%= f.text_field :enddate, :class => 'input-xlarge datepicker',:readonly => 'true' %>
            </div>
            <div class="field">
              <%= f.label :allocation %><br>
              <%= f.number_field :allocation, :class => 'input-xlarge',:min => '0',:max => (100 - @person.allocation), :step => '5' %>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>
        </div>

        <div class="modal-footer"></div>
        </div>
      </div>          
    </div>
  </div>

  <div class="modal" id="editPersonModal" tabindex="-1" role="dialog" aria-labelledby="newAssignmentModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
          <h4 class="modal-title" id="myModalLabel">Edit Details</h4>
        </div>
        <div class="modal-body">
          <%= form_for(@person) do |f| %>
          <% if @person.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>
              <ul>
              <% @person.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name,:class => 'input-xlarge name',:placeholder => "Person Name: eg. Andrew" %>
          </div>
          <div class="field">
            <%= f.label :skills %><br>
            <%= f.text_area :skills,:class => 'input-xlarge textArea',:placeholder => "Enter the skills: eg. Angular.js, Rails etc" %>
          </div>
          <div id="field">
            <%= f.label :location %><br>
            <%= f.select :location, options_for_select(getAllLocations,@person.location), {},{:class => "input-xlarge"} %>
          </div>
          <div class="field">
            <%= f.label :totalExp %><br>
            <%= f.text_field :totalExp, :class => 'input-xlarge numeric',:placeholder => "Total Experience in years: eg. 2.5",:step => "0.5",:min => "0"  %>
          </div>
          <div class="field">
            <%= f.label :tcsExp %><br>
            <%= f.text_field :tcsExp, :class => 'input-xlarge numeric',:placeholder => "TCS Experience in years",:step => "0.5",:min => "0" %>
          </div>
          <div class="field">
            <%= f.label :releventExp %><br>
            <%= f.text_field :relExp, :class => 'input-xlarge numeric',:placeholder => "Relevent Technology Experience in years",:step => "0.5",:min => "0" %>
          </div>
          <div class="field">
            <%= f.label :allocation %><br>
            <%= f.number_field :allocation ,:disabled=>true,:class => 'input-xlarge numeric' %>
          </div>
          <div class="field">
            <%= f.label :mobilenumber %><br>
            <%= f.number_field :mobilenumber, :class => 'input-xlarge phonenumber',:placeholder => "Enter Mobile Number: eg. 9571640968" %>
          </div>
          <div class="field">
            <%= f.label :emailid %><br>
            <%= f.text_field :emailid ,:disabled=>true,:class => 'input-xlarge email',:placeholder => "Email Address: eg. abc@xyz.com" %>
          </div>
          <div class="field">
            <%= f.label :interestAreas %><br>
            <%= f.text_area :interestAreas,:class => 'input-xlarge textArea',:placeholder => "Interested Areas: eg. Node.js" %>
          </div>
          <div class="field">
            <%= f.label :PersonalLearnings, "Personal Learnings :" %><br>
            <%= f.text_area :PersonalLearnings,:class => 'input-xlarge textArea',:placeholder => "PersonalLearnings" %>
          </div>
          <div class="field">
            <%= f.label :group_id %><br>
            <%= f.label Group.find(@person.group_id).name %>
            <input type="hidden" name="person[group_id]" value="<%= @person.group_id %>">
          </div>
          <div class="actions">
            <%= f.submit "Update" %>
          </div>
        <% end %>
      </div>

      <div class="modal-footer"></div>
      </div>
    </div>          
  </div>
    
<div class="col-md-6" id="ttt">
  <div class="scrollable" id="ttt">   
    <h4>Active Tasks:</h4>
    <table class="table table-striped">
    <% @assignments.each do |assignment| %>
      <% if (assignment.active) && (assignment.enddate - Time.now) > 0 %>
      <tr>
        <td>
          Project Name :
        </td>
        <td>
          <%= link_to getProject(assignment.project_id).name, project_path(getProject(assignment.project_id)) %>
        </td>
      </tr>
        <tr>
          <td>
            Allocation:
          </td>
          <td>
            <%= assignment.allocation %>
          </td>
        <tr>
          <td>
          </td>
          <td>
          <% if current_user.admin %>
            <a href="#" data-toggle="modal" data-target="#editAssignmentModal<%= assignment.id %>">
              <i class="glyphicon glyphicon-edit"></i>
            </a>
          <% end %>
          </td>
        </tr>
        <br>
        <% end %>

      <div class="modal" id="editAssignmentModal<%= assignment.id %>" tabindex="-1" role="dialog" aria-labelledby="editAssignmentModal<%= assignment.id %>" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
              <h4 class="modal-title" id="myModalLabel">Edit Assignment</h4>
            </div>
            <div class="modal-body">
              <%= form_for(assignment) do |f| %>
                <div class="field">
                  <strong>ID:</strong>
                  <%= assignment.id %>
                </div>
                <div class="field">
                  <%= f.label :billable %><br>
                  <%= f.check_box :billable %>
                </div>
                <p>
                  <strong>Group Name :</strong>
                  <%= Group.find(assignment.group_id).name %>
                </p>
                <p>
                  <strong>Project Name :</strong>
                  <%= Project.find(assignment.project_id).name %>
                </p>
                <p>
                  <strong>Person Name :</strong>
                  <%= Person.find(assignment.person_id).name %>
                </p>
                <div class="field">
                  <%= f.label :allocation %><br>
                  <%= f.text_field :allocation %>
                </div>
                <div class="field">
                  <%= f.label :startdate %><br>
                  <%= f.text_field :startdate ,:class => 'input-xlarge datepicker', :value => (assignment.startdate).strftime("%Y-%m-%d") %>
                </div>
                <div class="field">
                  <%= f.label :enddate %><br>
                  <%= f.text_field :enddate ,:class => 'input-xlarge datepicker', :value => (assignment.enddate).strftime("%Y-%m-%d") %>
                </div>
                <div class="actions">
                  <%= f.submit %>
                </div>
              <% end %>
            </div>

            <div class="modal-footer"></div>
            </div>
          </div>          
        </div>
      </div>
      <% end %>
    </table>
  </div>

  <div class="scrollable" id="ttt">
    <h4>History:</h4>
    <table class="table table-striped">
      <% @assignments.each do |assignment| %>
        <% if (!assignment.active) || (assignment.enddate - Time.now) < 0 %>
        <tr>
          <td>
            Project Name :
          </td>
          <td>
            <%= link_to getProject(assignment.project_id).name, project_path(getProject(assignment.project_id)) %><br>
          </td>
        </tr>
        <tr>
          <td>
            Allocation: 
          </td>
          <td>
            <%= assignment.allocation %>%<br>
          </td>
        </tr>
        <tr>
          <td>
            Assignment Duration:
          </td>
          <td>
            <%= distance_of_time_in_words(assignment.enddate,assignment.startdate).capitalize %>
          </td>
        </tr>
        <br><hr>
        <% end %>
      <% end %>
    </table>
</div>

<script>
  $(function() {
    <% hashProject = "[" %>
    <% @projects.each do |project| %>
    <% hashProject << "{ label: '" + project.name + "', value: '" + project.name.to_s + "' }," %>
    <% end %>
    <% hashProject.slice!(-1) %>
    <% hashProject << "]" %>
    $( "#tags" ).autocomplete({ source: <%= raw hashProject %>,
      messages: {
        noResults: '',
        results: function() {}
      }

     });
  });
  </script>