config/routes.rb
Rails.application.routes.draw do

  resources :people do
    get 'enable'
  end

  devise_for :users
  get 'welcome/index'
  resources :groups do
    get 'new_project'
    get 'projects'
    get 'people'
    get 'enable'
  end
  resources :projects do
    get 'enable'
  end
  resources :assignments

  root 'groups#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
	acts_as_xlsx
	has_many :people
	has_many :projects
	has_many :assignments

	validates :name, :presence => true, :length => { :minimum => 2 }
    validates :active, :presence => true

    def deactive
	  self.update_column :active, false
	end
	
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_group, only: [:show, :edit, :update, :destroy]
	def index
		@groups = Group.all 
	end

	def new_project

	end

	def projects
		#@people = Person.all
		@group = Group.find(params[:group_id])
		#@personnew = Person.new
		#@project = Project.new
		@projects = Project.where(:group_id => @group.id)
	end

	def people
		@group = Group.find(params[:group_id])
		@people = Person.where(:group_id => @group.id)
		#@personnew = Person.new
		#@project = Project.new
		#@projects = Project.all
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			redirect_to groups_path
		else
			render new_group_path
		end
	end

	def new
		@group = Group.new
	end

	def show
		@people = Person.where(:group_id => @group.id)
		@personnew =Person.new
		@assignments = Assignment.where(:group_id => @group.id) 
		
		if !@group.active?
			redirect_to edit_group_path(@group)
		else


			respond_to do |format|
			  format.html
			  format.xlsx
			end
		end
		
	end

	def edit

	end

	def update
		if @group.update(group_params)
			redirect_to groups_path(@group)
		else
			redirect_to edit_group_path(@group)
		end
	end

	def enable
		@group = Group.find(params[:group_id])
		@group.update_column :active, true
		if @group.save
			redirect_to groups_path
		else
			redirect_to groups_path
		end
	end

	def destroy
		
		@groupPeople = Person.where(:group_id => @group.id, :active => true)

		@groupProjects = Project.where(:group_id => @group.id, :active => true)



		if (!@groupProjects.empty?)
   			@groupProjects.each do |groupProject|
   				openAssignments = Assignment.where(:project_id => groupProject.id, :active => true)
   				openAssignments.each do |openAssignment|
   					openAssignment.deactive
   				end
   				groupProject.deactive
   			end
   		end

		if (!@groupPeople.empty?)
   			@groupPeople.each do |groupPerson|
   				groupPerson.deactive
			    # @openAssignments = Assignment.where(:person_id => groupPerson.id, :active => true)
   				# if (!@openAssignments.empty?)
   				# @openAssignments.each do |openAssignment|
	   			# 	# openAssignment.active = false
				   #  # openAssignment.enddate = Time.now
				   #  # openAssignment.save
				   #  openAssignment.deactive
				   #  groupPerson.allocation -= openAssignment.allocation
				   #  groupPerson.save
	   			# end
   				# end
   			end
   		end


		if @group.deactive
			redirect_to groups_path
		else
			redirect_to edit_group_path(@group)
		end
	end

	private
		def set_group
      		@group = Group.find(params[:id])
      		@personnew = Person.new
      		@groups = Group.all
      		@project = Project.new 
    	end

		def group_params
      		params.require(:group).permit(:name, :active)
    	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_sidebar.html.erb
<div class="sidebar">
	<a href="<%= group_path(@group) %>"><h3><%= @group.name %></h3></a>
	<hr>
	<ul class="nav nav-sidebar">
	  <li><a href="#" class="btn <%= "disabled" if !current_user.admin %>" data-toggle="modal" data-target="#newPersonModal">Add New Person</a></li>
	  <li><a href="#" class="btn <%= "disabled" if !current_user.admin %>" data-toggle="modal" data-target="#newProjectModal">Add New Project</a></li>
	  <li><a href="<%= group_people_path(@group.id) %>" class="btn">View People</a></li>
	  <li><a href="<%= group_projects_path(@group.id) %>" class="btn">View Projects</a></li>
	  <li><a href="<%= edit_group_path(@group.id) %>" class="btn <%= "disabled" if !current_user.admin %>">Settings</a></li>
	</ul>
</div>


	<div class="modal" id="newPersonModal" tabindex="-1" role="dialog" aria-labelledby="newPersonModal" aria-hidden="true">
	    <div class="modal-dialog">
	        <div class="modal-content">
	            <div class="modal-header">
		            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		            <h4 class="modal-title" id="myModalLabel">New Person</h4>
	            </div>
	            <div class="modal-body">
	                <%= form_for(Person.new) do |f| %>
					  <div class="field">
					    <%= f.label :name ,"Name :" %><br>
					    <%= f.text_field :name,:class => 'input-xlarge name',:placeholder => "Person Name: eg. Andrew" %>
					  </div>
					  <div class="field">
					    <%= f.label :skills ,"Skills :" %><br>
					    <%= f.text_area :skills,:class => 'input-xlarge textArea',:placeholder => "Enter the skills: eg. Angular.js, Rails etc" %>
					  </div>
					  <div class="field">
			            <%= f.label :location %><br>
			            <%= f.select :location, options_for_select(getAllLocations), {},{:class => "input-xlarge"} %>
			          </div>
					  <div class="field">
					    <%= f.label :totalExp, "Total Experience :" %><br>
					    <%= f.number_field :totalExp, :class => 'input-xlarge numeric',:placeholder => "Total Experience in years: eg. 2.5",:step => "0.5",:min => "0" %>
					  </div>
					  <div class="field">
					    <%= f.label :tcsExp, "TCS Experience :" %><br>
					    <%= f.number_field :tcsExp, :class => 'input-xlarge numeric',:placeholder => "TCS Experience in years",:step => "0.5",:min => "0" %>
					  </div>
					  <div class="field">
					    <%= f.label :relExp, "Relevant Experience :" %><br>
					    <%= f.number_field :relExp, :class => 'input-xlarge numeric',:placeholder => "Relevant Technology Experience in years",:step => "0.5",:min => "0" %>
					  </div>
					  <input type="hidden" name="person[allocation]" value="<%= 0 %>">
					  <div class="field">
					    <%= f.label :mobilenumber, "Mobile Number :" %><br>
					    <%= f.number_field :mobilenumber, :class => 'input-xlarge phonenumber',:placeholder => "Enter Mobile Number: eg. 9571640968" %>
					  </div>
					  <div class="field">
					    <%= f.label :emailid, "Email Address :" %><br>
					    <%= f.text_field :emailid,:class => 'input-xlarge email',:placeholder => "Email Address: eg. abc@xyz.com", :id => "checkmail" %>
					  </div>
					  <div class="field">
					    <%= f.label :interestAreas, "Interest Areas :" %><br>
					    <%= f.text_area :interestAreas,:class => 'input-xlarge textArea',:placeholder => "Interested Areas: eg. Node.js" %>
					  </div>
					  <div class="field">
					    <%= f.label :PersonalLearnings, "Personal Learnings :" %><br>
					    <%= f.text_area :PersonalLearnings,:class => 'input-xlarge textArea',:placeholder => "PersonalLearnings" %>
					  </div>
					  <input type="hidden" name="person[active]" value="<%= "true" %>">
					  <div class="field">
					    <%= f.label :group_id %> : 
					    <input type="hidden" name="person[group_id]" value="<%= @group.id %>">
					    <%= f.label @group.name %><br>
					  </div>
					  <div class="actions">
					    <%= f.submit "Create" %>
					  </div>
					<% end %>
	            </div>
	    </div>
	  </div>
	</div>


	<div class="modal" id="newProjectModal" tabindex="-1" role="dialog" aria-labelledby="newProjectModal" aria-hidden="true">
	    <div class="modal-dialog">
	        <div class="modal-content">
	            <div class="modal-header">
		            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		            <h4 class="modal-title" id="myModalLabel">New Project</h4>
	            </div>
	            <div class="modal-body">
	              <%= form_for(Project.new) do |f| %>

					  <div class="field">
					    <%= f.label :name %><br>
					    <%= f.text_field :name,:class => 'input-xlarge name',:placeholder => "Project Name: eg. Profiles" %>
					  </div>
					  
					  <div class="field">
					    <%= f.label :ProjectDetails %><br>
					    <%= f.text_area :ProjectDetails,:class => 'input-xlarge textArea',:placeholder => "ProjectDetails" %>
					  </div>
					  <div class="field">
					    <%= f.label :startDate %><br>
					    <%= f.text_field :startDate ,:class => 'input-xlarge datepicker',:readonly => 'true' %>
					  </div>
					  <div class="field">
					    <%= f.label :endDate %><br>
					    <%= f.text_field :endDate ,:class => 'input-xlarge datepicker',:readonly => 'true' %>
					  </div>
					  <input type="hidden" name="project[active]" value="true">
					  <div class="field">
					    <%= f.label :group_id %> : 
					    <input type="hidden" name="project[group_id]" value="<%= @group.id %>">
					    <%= f.label @group.name %><br>
					  </div>
					  <div class="actions">
					    <%= f.submit %>
					  </div>
				  <% end %>  
	            </div>
	    </div>
	  </div>
	</div>

app/views/groups/edit.html.erb
<div class="container">
<%= render 'groups/sidebar' %>
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
<%= f.label :name %>
<%= f.text_field :name %>
</div>
<div class="actions">
<%= f.submit "Update Name" %>
</div>
<% end %>
<br>
<% if @group.active? %>
<%= link_to 'Deactivate', @group, :class=> "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
<%= link_to 'Activate', group_enable_path(@group), :class=> "btn btn-sm btn-primary", data: { confirm: 'Are you sure?' } %>
<% end %>
</div>

app/views/groups/index.html.erb
<div class="row placeholders">
<% @groups.each do |group| %>
	<div class="col-xs-6 col-sm-3 col-md-3 placeholder">
	  
	  <h4><%= link_to group.name ,group_path(group) %></h4><br>
	  <a href="<%= group_path(group) %>"><img src="http://placehold.it/150x150/3276B1/ffffff&text=<%= group.name %>" /></a><br><br>
	</div>
<% end %>
</div>
<hr>
<% if current_user.admin %>
<div class="col-xs-6 col-sm-3 placeholder">
<button type="button" class="btn btn-primary"><%= link_to 'Add New Group' ,new_group_path %></button>
<div class="col-xs-6 col-sm-3 placeholder">
<% end %>

app/views/groups/new.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <input type="hidden" name="group[active]" id="group_active" value="<%= true %>">
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/new_project.html.erb
<div class="container">
  <div class="container-fluid">
    <div class="row">
     <%= render 'projects/new' %>
     <%= render 'groups/sidebar' %>
      
    </div>
  </div>
</div>

app/views/groups/people.html.erb
     <%= render 'groups/sidebar' %>
     <%= render 'people/index' %>      

app/views/groups/projects.html.erb
     <%= render 'groups/sidebar' %>
     <%= render 'projects/index' %>      

app/views/groups/show.html.erb
    <div class="row">
    <div>
    	<%= render 'groups/sidebar' %>
    </div>     

	<div>
		<%= render 'assignments/index' %>
	</div>

    </div>

app/views/groups/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Unallocated">
      <table>
        <Row>
          <Cell><Data ss:Type="String">Assignment ID/s</Data></Cell>
          <Cell><Data ss:Type="String">Name</Data></Cell>
          <Cell><Data ss:Type="String">Project</Data></Cell>
          <Cell><Data ss:Type="String">Billable</Data></Cell>
          <Cell><Data ss:Type="String">Allocation</Data></Cell>
        </Row>
       
        <% @people.each do |person| %>
        
        <% if (person.allocation != 100) && (person.allocation != 0) && (person.active?) %>
          <% @assignments = Assignment.where(person_id: person.id) %>
        <Row>
          <Cell><Data ss:Type="Number">
            <% @assignments.each do |assignment| %>
            <%= assignment.id %>,
            <% end %>
          </Data></Cell>
          <Cell><Data ss:Type="String">
              <a href="<%= person_path(person) %>"><%= person.name %></a>
          </Data></Cell>
          <Cell><Data ss:Type="String">
          <% @assignments.each do |assignment| %>  
            <a href="<%= project_path(Project.find(assignment.project_id)) %>"><%= Project.find(assignment.project_id).name %></a>              
            <% end %>
          </Data></Cell>
          <Cell><Data ss:Type="String">
            <% @finalBillable = false %>
            <% @assignments.each do |assignment| %>
              <% @finalBillable = @finalBillable || assignment.billable %>
            <% end %>
            <%= @finalBillable ? 'Yes' : 'No' %><br>
          </Data></Cell>
          <Cell><Data ss:Type="Number">
          <% @assignments.each do |assignment| %>
              <%= assignment.allocation %>,
            <% end %>
          </Data></Cell>
          </Row>
          <% end %>
          
      <% end %>
       
           


        
          <% @people.each do |person| %>
            <% if (person.allocation == 0) %>
            <Row>
                <Cell><Data ss:Type="Number"><%= "NA" %></Data></Cell>
                <Cell><Data ss:Type="String"><a href="<%= person_path(person) %>"><%= person.name %></a></Data></Cell>
                <Cell><Data ss:Type="String">
                <%= "Not Assigned" %>                 
                </Data></Cell>
                <Cell><Data ss:Type="String"><%= "NA" %></Data></Cell>
                <Cell><Data ss:Type="Number"><%= 0 %></Data></Cell>
              </Row> 
            <% end %>
          <% end %>
        </Worksheet>

    <Worksheet ss:Name="Allocated">
        <Row>
          <Cell><Data ss:Type="String">Assignment ID/s</Data></Cell>
          <Cell><Data ss:Type="String">Name</Data></Cell>
          <Cell><Data ss:Type="String">Project</Data></Cell>
          <Cell><Data ss:Type="String">Billable</Data></Cell>
          <Cell><Data ss:Type="String">Allocation</Data></Cell>
        </Row>
       
        <% @people.each do |person| %>
            <% if (person.allocation == 100) %>
            <Row>
              <% @assignments = Assignment.where(person_id: person.id) %>

              
                <Cell><Data ss:Type="Number">
                <% @assignments.each do |assignment| %>
                  <%= assignment.id %>,
                <% end %>
                </Data></Cell>
                <Cell><Data ss:Type="String">
                  <a href="<%= person_path(person) %>"><%= person.name %></a>
                </Data></Cell>
                <Cell><Data ss:Type="String"><% @assignments.each do |assignment| %>  
                  
                  <a href="<%= project_path(Project.find(assignment.project_id)) %>"><%= Project.find(assignment.project_id).name %></a> ,
                
                  
                  
                <% end %></Data></Cell>
                <Cell><Data ss:Type="String">
                  <% @finalBillable = false %>
                  <% @assignments.each do |assignment| %>
                    <% @finalBillable = @finalBillable || assignment.billable %>
                  <% end %>
                  <%= @finalBillable ? 'Yes' : 'No' %><br>
                </Data></Cell>
                <Cell><Data ss:Type="String"><% @assignments.each do |assignment| %>
                  <%= assignment.allocation %><br>
                <% end %>
                </Data></Cell>
                </Row> 
               


            <% end %>
          <% end %>
        </Worksheet> 
</Workbook>