config/routes.rb
Rails.application.routes.draw do

  resources :people do
    get 'enable'
  end

  devise_for :users
  get 'welcome/index'
  resources :groups do
    get 'new_project'
    get 'projects'
    get 'people'
    get 'enable'
  end
  resources :projects do
    get 'enable'
  end
  resources :assignments

  root 'groups#index'

end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= groups_path %>">Staffing App</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% @myProfile = Person.where(:emailid => current_user.email).first if user_signed_in? %>
        <% if !@myProfile.nil? %>
        <li><a href="<%= person_path(@myProfile) %>">My Profile</a></li>
        <% end %>
        <% if user_signed_in? && current_user.admin? %>
          <li><a href="<%= projects_path %>">Projects</a></li>
          <li><a href="<%= people_path %>">People</a></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path ,:method => :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>StaffingAppNew</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	<meta name="viewport" content="width=device-width, user-scalable=no">
	<%= csrf_meta_tags %>
</head>
<body>
	<!-- Top Nav bar -->
	<%= render 'layouts/nav' %>

	<!-- Notice and Alert Section -->
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<!-- Yielding of all views -->
	<div class="container">
		<%= yield %>
	</div>
	

	<!-- scripts -->
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>